<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <title><?php echo $city ?></title>
</head>

<body class='bg-light'>
    <div class='container-fluid bg-white sticky-top '>
        <form action="/location/search" method="get" class='form mx-auto mt-3 p-3'>
            <div class="input-group rounded">
                <input type="search" class="form-control rounded" name='search' placeholder="Search for different city" aria-label="Search" aria-describedby="search-addon" />
                <button type="submit">
                    <span class="input-group-text border-0" id="search-addon">
                        <i class="fas fa-search"></i>
                    </span>
                </button>
            </div>
        </form>
        <h2 class='text-center text-danger'>Displaying Results for <?php echo $city ?>!!</h2>

        <hr>
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="collapsibleNavbar">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="/location/details?<?php echo "action=current&city=$city" ?>">Current Weather</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/location/details?<?php echo "action=forecast&city=$city" ?>">Forecast(Today)</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/location/details?<?php echo "action=history&city=$city" ?>">History</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/location/details?<?php echo "action=timezone&city=$city" ?>">Time Zone</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/location/details?<?php echo "action=sports&city=$city" ?>">Sports</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/location/details?<?php echo "action=astronomy&city=$city" ?>">Astronomy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/location/details?<?php echo "action=alert&city=$city" ?>">Alerts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/location/details?<?php echo "action=airquality&city=$city" ?>">Air Quality</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <div class="container-fluid ">
        <div class="row mx-5 mt-2 px-5">

            <?php
            if ($action == 'sports') {
                foreach ($details as $key => $value) {
                    foreach ($value as $k => $v) {

            ?>

                        <div class="col-3 m-2 card">
                            <div class="card-body text-primary fw-bold"><?php echo $key; ?></div>
                            <div class="card-body "><?php
                                                    echo $v['tournament'] . "<br>" . $v['stadium'] . ", " . $v['country'] . "<br>" . $v['match'] . "<br>" . $v['start']
                                                    ?></div>
                        </div>
                    <?php }
                }
            } else {
                if ($details) {

                    foreach ($details as $key => $value) {
                        if ($key == 'condition' || ($action == 'current' && $key == 'air_quality')) continue;
                    ?>
                        <div class="col-3 m-2 card">
                            <div class="card-body text-primary fw-bold"><?php echo $key; ?></div>
                            <div class="card-body fs-4 fw-bold"><?php echo $value
                                                                ?></div>
                        </div>

                    <?php }
                } else {
                    ?>
                    <div class="col m-2 card text-center">
                        <div class="card-body text-primary fw-bold">No Alerts to show at this moment</div>

                    </div>
            <?php
                }
            }
            ?>

        </div>
    </div>

</body>

</html>