<span class="mt-5">.</span>
<h1 class='text-center pt-5 mt-5 text-white'>Search for Location...</h1>
<div id="cover">
    <form method="get" action="/location/search">
        <div class="tb">
            <div class="td"><input type="text" name='search' placeholder="Search" required></div>
            <div class="td" id="s-cover">
                <button type="submit">
                    <div id="s-circle"></div>
                    <span></span>
                </button>
            </div>
        </div>
    </form>
</div>