<body class='bg-light'>
    <div class='container bg-white sticky-top shadow-sm'>
        <form action="" method="get" class='form mx-auto mt-3 p-3'>
            <div class="input-group rounded">
                <input type="search" class="form-control rounded" name='search' placeholder="Search" aria-label="Search" aria-describedby="search-addon" />
            </div>
        </form>
        <h2>Displaying Results for <?php echo $city ?>!!</h2>
    </div>
    <div class="container mt-3">
        <?php foreach ($locations as $key => $value) {
        ?>
            <a href="/location/details?city=<?php echo $value['name'] . "&action=current" ?>">

                <div class="card">
                    <div class="card-body"><?php echo $value['url']; ?></div>
                </div>

            </a><br>
        <?php } ?>
    </div>
</body>